### ISSUE TITLE
Amun failing to start after running for 30 days 

### ISSUE THREAD

**Issue by Banisi69** [zeroq/amun#5]
I just came to restart my Amun as it was automatically stopped and i get the following error, i dont know what it means so please can someone help . :+1:   Traceback (most recent call last):
  File "amun_server.py", line 1273, in <module>
    runMain()
  File "amun_server.py", line 963, in runMain
    vuln_modules = readVulnModules(config)
  File "amun_server.py", line 615, in readVulnModules
    port_list = config.getSingleValue(mod_name).split(',')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Banisi69** [comment]
I fixed the issue by replacing the config file even tho nothing was changed
